### ISSUE TITLE
Janno->JSON translation needs to respect text representation in Janno file

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#72] opened 2021-03-18 07:26 UTC
We currently have a few quirks in the JSON translation, such as "," instead of ";" as list separator, and "Modern" instead of "modern". We need to go through all these datatype ToJSON/FromJSON instances and make sure they're consistent with the text representation of Janno data as defined in the original janno files.

**Comment by stschiff** [comment] 2021-04-20 11:47
@nevrome do you think this is an actual bug? I don't think it is right? The way we convert from JSON and to JSON just needs to be unique and correct, but there is - other than consistency - no particular reason why we can't use different list separator symbols in the JANNO format and in JSON.

**Comment by nevrome** [comment] 2021-04-20 11:59
This issue is not a bug - it's an enhancement suggestion :stuck_out_tongue: 

But I guess your question is, if we really have to change it. I would suggest to do so to maintain consistency. Inconsistencies like this are often a long-term mental burden.

**Comment by stschiff** [comment] 2021-04-20 12:00
OK, of course, makes sense!

**Comment by nevrome** [comment] 2023-01-11 11:26
Turns out that there is not much mental burden after all. I close this now.

**Closed by nevrome** 2023-01-11 11:26 UTC
Labels: enhancement
