### ISSUE TITLE
Problem installing trident with conda (MacOS)

### ISSUE THREAD

**Issue by jbv2** [poseidon-framework/poseidon-hs#279] opened 2023-10-23 14:25 UTC
I created an environment and tried to install it on a Mac M1 with:
`conda create -n poseidon -c bioconda poseidon-trident`

I didn't receive any error messages. 
I then typed `trident` and got:
```
❯ trident
[1]    24251 segmentation fault  trident

❯ trident --help
[1]    24259 segmentation fault  trident --help

❯ which trident
/Users/judith_ballesteros/miniconda3/envs/poseidon/bin/trident
```

In the same environment, I installed xerxes with:
`❯ conda install -c bioconda poseidon-xerxes`
It functioned properly.

I tried removing trident and reinstalling it. Also with the previous version (1.2.0.0), and got the same error.

Downloading the executable for MacOS functioned properly.

**Comment by nevrome** [comment] 2023-10-27 09:59
Thanks for reporting this!

I thought this could be related to #247, but if the static executable works, then can probably not be it. But we also have a version mismatch: The trident version in conda is still the older `1.3.0.4`, whereas I assume @jbv2 downloaded the executable `1.4.0.2` when she installed it without conda.

I'm trying to piece together if we need the Apple Silicon build and whether it would help to solve this issue. The [conda recipe for trident](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/poseidon-trident/meta.yaml) is super simple: It just wraps the pre-built executable. For linux we need a special executable, but for macOS we just take the normal one. Why does it not work through conda?

@jbv2 Does other software work if you install it through conda?  I think conda only added Apple Silicon support last year. Could you also quickly check if the old trident executable 1.3.0.4 works, if you download it directly from [here](https://github.com/poseidon-framework/poseidon-hs/releases/download/v1.3.0.4/trident-macOS)?

@TCLamnidis Could you quickly confirm or deny if `conda create -n poseidon -c bioconda poseidon-trident` works for you on macOS? You don't have Apple Silicon, right?

**Comment by stschiff** [comment] 2023-10-27 11:11
Thanks for raising this, @jbv2. I will try it out, too, I have an M2-Chip.

**Comment by stschiff** [comment] 2023-10-30 15:25
Hmm... I'm really not a conda-user, so I can't really figure out what's going on here, but for me it doesn't even find the packages:

```
stephan_schiffels@BIONB100-2 ~ % conda create -n poseidon -c bioconda poseidon-trident
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - poseidon-trident

Current channels:

  - https://conda.anaconda.org/bioconda/osx-arm64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

the same for xerxes. @TCLamnidis any hints?

**Comment by TCLamnidis** [comment] 2023-11-01 14:38
I had no issue finding/installing both trident and xerxes with conda and they ran fine.

I think the issue is that bioconda is working on implementing package recipes for ARM chips (`osx-arm64` vs the older `osx-64` channel). It seems that your conda picks up your chipset and tries to pull recipes from the new channel, which is empty afaik.

```
Current channels:

  - https://conda.anaconda.org/bioconda/osx-arm64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch
  ```
  
  You can try to specifically pull from the `osx-64` channel by enabling that subdirectory.
  ```
  CONDA_SUBDIR=osx-64 conda create -n poseidon -c bioconda poseidon-trident poseidon-xerxes
  ```

**Comment by TCLamnidis** [comment] 2023-11-01 14:47
See further discussions [here](https://stackoverflow.com/questions/65415996/how-to-specify-the-architecture-or-platform-for-a-new-conda-environment-apple)

**Comment by nevrome** [comment] 2023-11-01 15:04
Nice! Thanks for investigating!

What would it cost to make our executable(s) available for the `osx-arm64` channel? So that users don't have to consider this?

**Comment by TCLamnidis** [comment] 2023-11-01 15:07
I don't think it is possible to add things to the `osx-arm64` channel yet. It's upcoming: https://github.com/bioconda/bioconda-recipes/pull/40550

However, if the pre-compiled binaries are usable in both chipsets, it should be as easy as publishing them to both channels instead of just one. To be don once the new channel is live

**Comment by nevrome** [comment] 2023-11-02 08:48
Ah - ok!

I'll pin this issue then for future reference.

**Comment by nevrome** [comment] 2024-07-11 14:08
![image](https://github.com/poseidon-framework/poseidon-hs/assets/10789038/6d1351fb-4b71-46b7-ae40-854df5a1acb9)

The new bioconda channel seems to be available now. That means we can try to place our macOS ARM64 executable there. I'll try to remember this for the next trident release.

**Comment by nevrome** [comment] 2024-07-12 15:32
The ARM64 executable is online now for the new trident release v1.5.4.0: https://anaconda.org/bioconda/poseidon-trident

![image](https://github.com/user-attachments/assets/2874d4a7-4114-47fb-a7ee-dc643fb480dc)

Please give it a try, @jbv2! Because I'm pathologically optimistic about these builds I'll close this issue now. Please reopen, if that was premature!

**Closed by nevrome** 2024-07-12 15:32 UTC
Labels: to be resolved when possible
