### ISSUE TITLE
Package out server to separate repo

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-hs#204] opened 2022-11-04 13:33 UTC
I think I would like to package out the server code to a new Haskell package and repo. It becomes a bit annoying that we have only one version system for both trident and the server... I need to make further updates to the server, and I don't want to create unnecessary version updates if trident itself hasn't changed. What do you think, @nevrome ?

**Comment by nevrome** [comment] 2022-11-05 15:59
In principle yes... But to avoid code duplication (encoding and decoding in one system) this new executable should depend on poseidon-hs, right? And then we have to remember to adjust the commit hash for poseidon-hs in the new `stack.yaml` file. Feels like a potential point of annoyance. I would bet money that this will be the cause of more than mismatch between client and server. What do you think?

Also: If we want to be correct, then we should consider to factor out trident, to get three repos: library, trident and server. Would feel a lot cleaner than just randomly taking the server out. poseidon-analysis-hs could then depend on the library only, making this dependency lighter as well.

**Comment by nevrome** [comment] 2022-11-05 16:02
If the only problem right now is versioning, then I think we should first consider other solutions to the way we do releases. Before we consider some big refactoring exercise. GitHub releases are not our only option, after all. Especially not for something like the server, which probably no user will ever run.

**Comment by stschiff** [comment] 2022-11-09 11:35
yeah OK. I will postpone this for now. Indeed, in the end having library, trident and server in separate packages might be the best, but it's also some work, perhaps we shouldn't prioritise this now.

**Comment by nevrome** [comment] 2023-04-14 13:48
After we getting some feedback from the Haskell community [on reddit](https://old.reddit.com/r/haskell/comments/127mlcn/project_layout_with_multiple_interconnected/) we're leaning more towards integration than splitting (Mono-repo). So I'll close this specific issue for now.

**Closed by nevrome** 2023-04-14 13:48 UTC
Labels: for the future
